version: '2'
services:
  approp-api-db:
    image: mysql:5.7.18
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4ppr0pdb2017
    ports:
      - "3307:3306"

  approp-api:
    container_name: approp-api
    build: .
    env_file: .env
    depends_on:
      - approp-api-db
    links:
      - approp-api-db
    environment:
      - RAILS_ENV=development
    volumes:
      - publicimages:/usr/src/app/public/uploads
    ports:
      - "3000:3000"

volumes:
  publicimages:
    external: true