defaults: &defaults
  DB_PASS: "root"
  DB_USER: "root"
  DB_POOL: "5"

development:
  <<: *defaults

test:
  <<: *defaults
  DB_PASS: "4ppr0pdb2017"
  DB_USER: "root"
  DB_POOL: "10"

production:
  <<: *defaults
  DB_PASS: "4ppr0pdb2017"
  DB_USER: "root"
  DB_POOL: "10"