# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: approp_development
  username: root

#  Passwrod Local
  password: root

#  Password DO
#  password: approp

#  El host es necesario para contruir la imagen con docker y su post deploy en DO, comentarlo para ambiente local
#  host: approp-db
  reconnect: true

#  Se comentan los sockets para el deploy en DO

#  Socket ubuntu
#  socket: /opt/lampp/var/mysql/mysql.sock

#  Socket IOS
#  socket: /tmp/mysql/mysql.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
