# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#DigitalOcean
#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: 5
#  database: approp_development
#  username: root
#  password: approp
#  host: approp-db
#  reconnect: true

#Localhost
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: approp_development
  username: root
  password: root
  reconnect: true
#  socket: /opt/lampp/var/mysql/mysql.sock


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
